- name: "Deploy static webapp in instance"
  hosts: "{{ target | default('no_hosts')}}"
  tasks:
  - name: "Pull webapp files"
    shell: |
      git clone {{APP_GIT_REPO_URL}} app

  - name: "Serve app"
    shell: |
      cd app
      nohup ./run.sh </dev/null >/dev/null 2>&1 &
      # TODO create new user to run website instead of root as done here
      # Add caddy to startup ?
    
    # Webapp dynamique : setup des composants
    
# ---------------------------------------------------------------------
# TODO make sure webapp responds on container http port : loop with curl
